package com.example.demo.Model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

/**
 * 📝 Question Entity - The Building Block of Our Quizzes!
 * 
 * This class represents a single quiz question in our database.
 * Each question is like a puzzle piece that users need to solve.
 * 
 * Think of it as a multiple-choice question card with:
 * - The actual question text
 * - Four possible answers to choose from
 * - One correct answer (shh! 🤫)
 * - Category (like "Java", "Python", "JavaScript")
 * - Difficulty level (Easy, Medium, Hard)
 * 
 * The @Entity annotation tells Spring "Hey, save this to the database!"
 * The @Data annotation from Lombok automatically creates getters/setters for us.
 * 
 * @author KUNAL M
 * @version 1.0
 */
@Data
@Entity
public class Question {
	
	/** 🆔 Unique identifier for each question - like a question's fingerprint! */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	
	/** ❓ The actual question text that users will see and answer */
	private String question_title; 
	
	/** 🅰️ First possible answer choice */
	private String option1;
	
	/** 🅱️ Second possible answer choice */
	private String option2;
	
	/** 🅲 Third possible answer choice */
	private String option3;
	
	/** 🅳 Fourth possible answer choice */
	private String option4;
	
	/** ✅ The correct answer (one of the four options above) */
	private String right_answer;
	
	/** 📊 How hard is this question? (Easy/Medium/Hard) */
	private String difficultylevel;
	
	/** 📚 What subject does this question belong to? (Java/Python/etc.) */
	private String category;
	
	// 🔧 Getters and Setters (automatically generated by @Data, but included for clarity)
	
	public int getId() {
		return id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	public String getQuestion_title() {
		return question_title;
	}
	
	public void setQuestion_title(String question_title) {
		this.question_title = question_title;
	}
	
	public String getOption1() {
		return option1;
	}
	
	public void setOption1(String option1) {
		this.option1 = option1;
	}
	
	public String getOption2() {
		return option2;
	}
	
	public void setOption2(String option2) {
		this.option2 = option2;
	}
	
	public String getOption3() {
		return option3;
	}
	
	public void setOption3(String option3) {
		this.option3 = option3;
	}
	
	public String getOption4() {
		return option4;
	}
	
	public void setOption4(String option4) {
		this.option4 = option4;
	}
	
	public String getRight_answer() {
		return right_answer;
	}
	
	public void setRight_answer(String right_answer) {
		this.right_answer = right_answer;
	}
	
	public String getDifficultylevel() {
		return difficultylevel;
	}
	
	public void setDifficultylevel(String difficultylevel) {
		this.difficultylevel = difficultylevel;
	}
	
	public String getCategory() {
		return category;
	}
	
	public void setCategory(String category) {
		this.category = category;
	}
}
