package com.example.demo.Model;

import lombok.Data;

/**
 * 📝 Response Model - Capturing User's Quiz Answers!
 * 
 * This simple class represents a user's answer to a specific question.
 * Think of it as a student's answer sheet where each response corresponds to one question.
 * 
 * For example:
 * - Question ID: 5 (Which method starts a Java program?)
 * - User's Response: "main()" 
 * 
 * When a user submits their quiz, we get a list of these Response objects,
 * one for each question they answered. Then we can check if their responses
 * match the correct answers and calculate their score!
 * 
 * Note: This is NOT a database entity (no @Entity annotation) because
 * it's just a temporary holder for data during quiz submission.
 * 
 * @author KUNAL M
 * @version 1.0
 */
@Data
public class Response {
	
	/** 🆔 The ID of the question this response is answering */
	private int id;
	
	/** 💬 The user's chosen answer (e.g., "option1", "option2", etc.) */
	private String response;
	
	/**
	 * 🏗️ Default constructor - creates an empty response
	 * Perfect for when we're initializing response objects!
	 */
	public Response() {
		super();
		// Ready to capture user's answers! 🎯
	}
	
	// 🔧 Getters and Setters (automatically generated by @Data, but included for clarity)
	
	public int getId() {
		return id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	public String getResponse() {
		return response;
	}
	
	public void setResponse(String response) {
		this.response = response;
	}
}
